//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election_Hackathon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hackathon_KarnatakaEntities : DbContext
    {
        public Hackathon_KarnatakaEntities()
            : base("name=Hackathon_KarnatakaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate_Registration_Form> Candidate_Registration_Form { get; set; }
        public virtual DbSet<General_Details> General_Details { get; set; }
    }
}
