//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election_Hackathon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_Details()
        {
            this.Candidate_Registration_Form = new HashSet<Candidate_Registration_Form>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Register_Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_Registration_Form> Candidate_Registration_Form { get; set; }
    }
}
