// <auto-generated />
namespace Election_Hackathon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingvalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingvalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040740055_addingvalidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
